forms_runner:
  url: https://submit.forms.service.gov.uhrblx.com

forms_product_page:
  support_url: https://www.forms.service.gov.uhrblx.com/support

features:
  multiple_branches: true

# Use real authentication
auth_provider: gds_sso

mailchimp:
  api_prefix: "us12"
  active_users_list: c9cc8511c6
  mou_signers_list: ef5e72c003
